### PR TITLE
Extended cooling option - use cooling settings for other parts.

### PR DESCRIPTION
**Pull request by vovodroid**
New options:
image

Assuming we have default speed zero we can set another speed for additional parts.

Set bridge fan and print speeds for all layers above bridge to prevent sagging, especially for 100% infill :
image
image
image

Set internal bridge fan and print speeds for first solid layer over internal bridge:
image

Use top fan speed for all solid infill:
image

Use external perimeter fan speed for internal perimeter:
image

Always use the same speed (e.g. 100%) for both support material and interface, as material needs stability:
image

### CODE REVIEW

**Comment by Lt-Kammello** [comment]
Would be great to have an option for the different speeds so that they can override automatic cooling fan speed.
My problem is that i have CPAP fan and lot of air pressure, i just need very low cooling on unsupported bridges, but on small parts fan runs fast due to autocooloing.
So fast that the bridge lines literally get pushed down.

**Comment by vovodroid** [comment]
So would you like to set low fan speed for bridges? But you can do this with current SS version.

**Comment by Lt-Kammello** [comment]
> So would you like to set low fan speed for bridges? But you can do this with current SS version.

I can set a fixed bridge_fan_speed, but as stated in the description in SS:

> This fan speed is enforced during bridges and overhangs. It wont slow down the fan if it's currently running at higher speed.

The behaviour is as follows: when automatica coolin fan speed is higher than the set fixed bridge_fan_speed, the parameter is ignored and the higher resulting calculated fan speed based on layer time is used instead.

This logic might be ok for average small fans printers since they have not enough air pressure to push down the bridged lines, but with higer pressure systems the issue is evident.
Either you set the max fan speed for autocooling to a lower value, sacrificing the benefit of hi cooling volume for hi speed printing or you basically can't use bridges and are forced to use support everywere.

I see your excellent rework of cooling parameters as an occasion to add an option/setting such as enforce_fan_speed_over_autocooling in order to change the behaviour and allow the fixed fan speed you set to override autocooling fan speed.
Also i think that your work would be much more complete because, on smaller (short layer timed) prints, your added and reworked colling parameters are all overridden by the autocooling speed.

Lorenzo

**Comment by vovodroid** [comment]
@Lt-Kammello, like this:

image

image


If you want to build SS by yourself just comment out lines:
https://github.com/supermerill/SuperSlicer/blob/nightly_dev/src/libslic3r/GCode/CoolingBuffer.cpp#L876
https://github.com/supermerill/SuperSlicer/blob/nightly_dev/src/libslic3r/GCode/CoolingBuffer.cpp#L886 (and next one)
And replace https://github.com/supermerill/SuperSlicer/blob/nightly_dev/src/libslic3r/GCode/CoolingBuffer.cpp#L910 with `bridge_fan_control = true;`

**Comment by Lt-Kammello** [comment]
@vovodroid 

I asked a friend to modify the cooling logic in SS, we performed the following changes to the code:

I would like to modify a code for more performance about my project.

THIS IS CODE NOW:

           if (layer_time < slowdown_below_layer_time && fan_below_layer_time > 0) {
                // Layer time very short. Enable the fan to a full throttle.
                fan_speed_new = std::max(max_fan_speed, fan_speed_new);
                bridge_fan_speed = std::max(max_fan_speed, bridge_fan_speed);
                bridge_internal_fan_speed = std::max(max_fan_speed, bridge_internal_fan_speed);
                ext_peri_fan_speed = std::max(max_fan_speed, ext_peri_fan_speed); // cannot be ovveridden
MY CODE:

           if (layer_time < slowdown_below_layer_time && fan_below_layer_time > 0) {
                // Layer time very short. Enable the fan to a full throttle.
                fan_speed_new = std::max(max_fan_speed, fan_speed_new);
                bridge_fan_speed = fan_speed_new;
                bridge_internal_fan_speed = fan_speed_new;
                ext_peri_fan_speed = std::max(max_fan_speed, ext_peri_fan_speed); // cannot be ovveridden 
                
                
Here's the link to the ticket, i would appreciate your contribution if you wish.

https://github.com/supermerill/SuperSlicer/issues/3764

**Comment by legend069** [comment]
we've got a bit of a "double" PR here https://github.com/supermerill/SuperSlicer/pull/3735

i like the feature for extra cooling on areas above a bridge, is there a GUI option to enable/disable that ?

**Comment by vovodroid** [comment]
> we've got a bit of a "double" PR here #3735

Yes, I wanted some control for cooling, so did it simpler. Your PR obviously more flexible (though I'm not sure whether such fine control is needed).


> , is there a GUI option to enable/disable that ?

Yes, it's this one:
image

**Comment by legend069** [comment]
> Yes, I wanted some control for cooling, so did it simpler. Your PR obviously more flexible (though I'm not sure whether such fine control is needed).

yeah that is a good point. but then the in depth acceleration control is not needed for the basic user.

regarding the fan speed above the bridges, it would be good to have a variable for that 
`apply bridge fan speed above a bridge area for x extra layers then revert back to normal fan speeds`

**Pull request closed without merging**
