### PR TITLE
Semi-parallel (range) printing

### PR DESCRIPTION
**Pull request by vovodroid**
It prints different objects not layer by layer, but by layer range, i.e. prints some heights (usually 3-5mm) of every object and then move to the next.

image

image

See also #3335.

Limitation:
- it doesn't work with wipe tower
- it doesn't work with object instances. As workaround instances could be split to separate objects.

I guess that PR is not in a line of existing code architecture, but probably could be used as base for more elegant and robust solution.

### CODE REVIEW

**Comment by vovodroid** [comment]
Here is images with this PR working:

image

image

image

image

**Comment by supermerill** [comment]
I didn't see any change in the cooling file.
I fear that the cooling time requirements can also be messed up with it.

I'm not against the idea, bt it may need further dev.

**Comment by supermerill** [comment]
merged
i changed the tooltip, tell me if you want to edit something.

**Comment by supermerill** [comment]
note to self: re-review after ps merge

**Comment by vovodroid** [comment]
> note to self: re-review after ps merge

Hi, nice to meet you here!
I have the same PR in Prusa, with updated code https://github.com/prusa3d/PrusaSlicer/pull/11168
Also it's better to replace two option with one enum like {None, Complete, Range).

**Comment by vovodroid** [comment]
Merged

**Comment by Lecso11** [comment]
Noticed some bug with this on #4004

**Pull request closed without merging**
