### PR TITLE
Add preference to disable changing focus due to mouse movement

### PR DESCRIPTION
**Pull request by RealDeuce**
A longstanding irritant to me has been if I'm editing a value (such
as the model X position) and I move the mouse over the platter, focus
is lost in the input box, and digits and tab behave in unexpected ways.

This is due to the canvas taking focus on mouse movement apparently so
that keyboard shortcuts for the items in the left bar work.  Since I've
never tried to use those keyboard shortcuts, it's more important to me
that the input box I clicked on receives the input I try to enter than
being able to use keyboard shortcuts for something else.

I've been using this change on my local branch for a while now on FreeBSD and haven't encountered any issues, but I have not tested it on Windows or macOS, and upstream appears to place a very high importance on the gizmo shortcuts working.

### CODE REVIEW

**Comment by supermerill** [comment]
yes, it also annoy me a lot.
But as you said, it's useful for answering input.
Maybe it's possible to intercept these events at the window/application level, so we can stop using 'plater focus'

**Comment by RealDeuce** [comment]
> Maybe it's possible to intercept these events at the window/application level, so we can stop using 'plater focus'

That would maybe be possible for numeric only input boxes, but for text input boxes (like the "name" column) it wouldn't really work.  Traditionally, this problem is solved by using a modifier key (Control, Alt, Option, Command, Windows, Meta, Menu, whatever)

I would be willing to take a stab at using Alt/Option for all of those keys - though Ctrl-Alt-Delete for "delete all" should likely be changed then. ;)

Or maybe Control for the top bar and Alt for the left bar?

So the top bar changes:
[Del] -> [Shift+Del] (Because Ctrl-Del is delete all)
[Ctrl+A] for Arrange, [Ctrl+Shift+A] for arrange selection
[Ctrl++] to add instance
[Ctrl+-] to remove instance

Left bar changes:
[Alt+M] for move
[Alt+S] for scale
[Alt+R] for Rotate
[Alt-F] for Place on Face
[Alt-C] for Cut Object
[Alt-L] for Paint-on supports
[Alt-P] for Seam painting

**Comment by RealDeuce** [comment]
So I guess *technically* it would be possible to have a custom input box that passes out unhandled keystrokes, but I think it would be terrible to do that... not only would the interface be weirdly modal, it would also be somewhat of a localization nightmare (command vs. period is the obvious one).

Also, I just remembered about the camera controls (0-6), I would make those Ctrl-number as well I think.

**Comment by RealDeuce** [comment]
So, actually looking at the Keyboard Shortcut help, this is a nightmare... I'll chew through all the existing stuff and see what I can come up with.

**Comment by RealDeuce** [comment]
Ok, the whole shortcut thing is just too big of a task at least for now (I'm trying to build my next printer), how about a preference that defaults to the current behaviour, but allows turning it off?

**Comment by supermerill** [comment]
> how about a preference that defaults to the current behaviour, but allows turning it off?

that's an acceptable compromise

**Comment by RealDeuce** [comment]
FYI, this PR has the preference update in it.

**Comment by supermerill** [comment]
merged in dev branch

**Pull request closed without merging**
