### PR TITLE
Added Client certificate authentication to physical printer options #2269

### PR DESCRIPTION
**Pull request by Pieterv24**
Due to some issues with merging the master branch in PR #2283 I've recreated this PR.
This PR only contains my changes, added onto a clean master branch.

Latest changes:
- Added a toggle for adding a client cert.
- Added a password field, to use with password protected client certificate files.

Todo list:
- Build/Test on MacOS
- Build/Test on Windows

Any suggestions on how I can build these and test them would be appreciated

### CODE REVIEW

**Comment by supermerill** [comment]
why adding printhost_client_cert_enabled?
other fields rely on emptiness to disable themselves.

**Comment by Pieterv24** [comment]
> why adding printhost_client_cert_enabled? other fields rely on emptiness to disable themselves.

The idea behind it was to unclutter the UI.
However if you believe it shouldn't be there, I will remove it.

**Comment by Pieterv24** [comment]
> > why adding printhost_client_cert_enabled? other fields rely on emptiness to disable themselves.
> 
> The idea behind it was to unclutter the UI. However if you believe it shouldn't be there, I will remove it.

There is also the thing that on macos the cert is taken from the keychain, so no file needs to be selected.
A simple enable button would do there

**Comment by Pieterv24** [comment]
So for windows and linux everything is working as expected.
Just add the file and (if needed) the password.

However on MacOS (this is tested on monterey on a intel machine). When I select a file, it asks access to my keychain.
And after if it's a valid cert, it doesn't matter if I add the client cert header.
Still trying to figure out the working of libcurl on macos, because I don't really get reproducable results.
If unable to find it, I'll probably disable it on macos for the time being

**Comment by Pieterv24** [comment]
So I found due to the way macos works with certs, you need to either add it to your keychain or select a file (this will be added to your keychain) in order for this to work.

To deal with this i've added some instructions

**Comment by supermerill** [comment]
> The idea behind it was to unclutter the UI.
> However if you believe it shouldn't be there, I will remove it.

No problem with the ui.
But I wonder if it's useful to save it as a setting.

**Comment by Pieterv24** [comment]
> > The idea behind it was to unclutter the UI.
> > However if you believe it shouldn't be there, I will remove it.
> 
> No problem with the ui, I agree But I wonder if it's useful to save it as a setting. If it's a setting, i have to make sure to handle as a legacy setting if something change. I can see a use to "keep" the cert path, but I don't think there is a big need to enable/disable the cert often.
> 
> I can remove the enable setting myself, just asking if It's important to keep that this way.

You made a good point.
After figuring out how the cert store works on MacOS, I don't see any use for it anymore either.
I've removed the enable toggle.

**Comment by supermerill** [comment]
merged.
I added a gui-only checkbox, as you set it previously.

**Pull request closed without merging**
