### PR TITLE
Show layer time

### PR DESCRIPTION
**Pull request by vovodroid**
Show layer time in ruler

image

image

### CODE REVIEW

**Comment by supermerill** [comment]
Merge into nigthly
i've added two preference option to enable/disable the layer height & time in the scrollbar.
also fixed the layer id.

**Comment by 5axes** [comment]
From my point of view, the most interesting thing is not to have the time per layer, but the total time at the layer level, to be able to estimate the waiting time to reach a certain print level.

**Comment by vovodroid** [comment]
There is cumulative time here:
image

Layer time could be useful for cooling estimation and tuning.

**Comment by 5axes** [comment]
It's true ... but not very practical .... you have to move on the layer with the mouse and then move the cursor with the mouse wheel (if you have a wheel) to see the total time hidden behind the layer height info. 
image

**Pull request closed without merging**
