### PR TITLE
Created shell script to build SuperSlicer on macOS

### PR DESCRIPTION
**Pull request by eisen**
This script is only needed to build locally

### CODE REVIEW

**Comment by supermerill** [comment]
I modified it a bit (split in two).
can you check that it works? It's on the Nightly branch.

**Comment by eisen** [comment]
I can't find the build/BuildMacOSImage.sh and build/BuildLinux.sh scripts.

My only concern is that there is a lot of commonality in the two scripts. If the build process changes, there are two places to update instead of one. Maybe we can rename the original script and add checks for Linux or Mac.

**Comment by csch0** [comment]
I would keep the log files separate for each step but thats personal opinion and nothing crucial, but I would add ```set -e``` to the bash file.

E.g. I checked it on my mac and cmake was not found, but the script said everything is fine. I don't want to make it bullet proved but to cancel the build on error is a good thing.

Just trying the script, but the Air is just soooo slow. :D

**Comment by supermerill** [comment]
> I can't find the build/BuildMacOSImage.sh and build/BuildLinux.sh scripts.

These are compiled by cmake from the src/plateform/osx/BuildMacOSImage.sh.in , etc...

> My only concern is that there is a lot of commonality in the two scripts. If the build process changes, there are two places to update instead of one. Maybe we can rename the original script and add checks for Linux or Mac.

It's to leverage the version.inc file: name & version of the software shouldn't be hardcoded.

**Comment by lbibass** [comment]
Just an FYI, the current build script does not, and cannot, make a macOS DMG. It's completely broken.

**Comment by eisen** [comment]
> > I can't find the build/BuildMacOSImage.sh and build/BuildLinux.sh scripts.
> 
> These are compiled by cmake from the src/plateform/osx/BuildMacOSImage.sh.in , etc...
> 
> > My only concern is that there is a lot of commonality in the two scripts. If the build process changes, there are two places to update instead of one. Maybe we can rename the original script and add checks for Linux or Mac.
> 
> It's to leverage the version.inc file: name & version of the software shouldn't be hardcoded (when possible)

Ok, working on it. My cmake is not generating the build/BuildMacOSImage.sh and build/BuildLinux.sh scripts.

**Comment by eisen** [comment]
Ok, I got the Mac script working. Applied the same changes to the Linux script will need someone to test it.

**Comment by supermerill** [comment]
perfect, I merge it.

**Comment by csch0** [comment]
@eisen checked it on Linux, found 2 things, will create a PR for your branch.

**Comment by supermerill** [comment]
should be ok.

**Comment by lbibass** [comment]
It's not working for me. ```chmod: /Users/lbibass/git/superslicer/build/src/BuildMacOSImage.sh: No such file or directory
./BuildMacOS.sh: line 110: /Users/lbibass/git/superslicer/build/src/BuildMacOSImage.sh: No such file or directory```

**Comment by lbibass** [comment]
I think I know why. 

```/Users/lbibass/git/superslicer/src/libslic3r/GCode/GCodeProcessor.cpp:2533:9: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]```

The compile itself is broken.

**Comment by dmnkhhn** [comment]
> `/Users/lbibass/git/superslicer/src/libslic3r/GCode/GCodeProcessor.cpp:2533:9: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]`

Same error here (macOS 11.4), after running `make Slic3r`

**Comment by supermerill** [comment]
I'll fix that.

**Comment by lbibass** [comment]
> I'll fix that.

The compile still fails, unfortunately. 

```/Users/lbibass/git/superslicer/deps/build/destdir/usr/local/include/boost/multiprecision/cpp_int/limits.hpp:27:36: error: ambiguous conversion for functional-style cast from 'number<boost::multiprecision::backends::cpp_int_backend<128, 128, boost::multiprecision::unsigned_magnitude, boost::multiprecision::unchecked, void>, et_off>' to 'result_type' (aka 'number<boost::multiprecision::cpp_int_backend<128U, 128U, (cpp_integer_type)1U, (cpp_int_check_type)0U, void>, (boost::multiprecision::expression_template_option)0U>')
   static const result_type val = -result_type(~ui_type(0));```

**Pull request closed without merging**
