### PR TITLE
Round and show layer height

### PR DESCRIPTION
**Pull request by vovodroid**
PR for #3381, copy there:

When using variable layer height feature height is shown with too much trailing zeroes or decimals, though it's rounded to Z full step parameter. I've done it in GLCanvas3D.cpp:

image

Also I've added layer height to slider:

image

### CODE REVIEW

**Comment by supermerill** [comment]
thanks
merged in dev branch

**Comment by vovodroid** [comment]
Great to hear!

What is purpose of **dev** and **nightly_dev**? Which one is most updated and where develop new features?

**Comment by vovodroid** [comment]
Merged by @supermerill

**Comment by vovodroid** [comment]
By a way, actually it could be done much simpler - just round layer height in GUI to 0.01 without manipulating with each layer height.

**Pull request closed without merging**
