### PR TITLE
extended cooling options

### PR DESCRIPTION
**Pull request by legend069**
extended cooling options

superslicer_bAYiv8ZkK2

big overhaul to cooling options, most important extrusion roles are now independently supported.  tested several months in real world and gcode viewer all seems stable.

main important cooling options work as expected. can't find any bugs with important parts.

couple small bugs found introduced or already existed.
bridge infill fan speeds getting set when also using full_fan_speed_layer
fan_speed_up_time and fan_kickstart sometimes don't work correctly.

only tested with gcode-flavor being klipper. will assume the others will be fine too, since marlin still uses m106 for fan commands.
additions:
cooling options for; internal infill, solid infill,internal perimeter, overhang perimeter, gap fill

couple of small bug fixes with cooling options.
1. double ups of m106 for other extrusion roles before the extrusion role starts.
2. several unnecessary m107's no longer get applied to gcode.

### CODE REVIEW

**Comment by legend069** [comment]
issues ect where requested. there is a fair amount of it.

https://github.com/supermerill/SuperSlicer/issues/3568
https://github.com/supermerill/SuperSlicer/issues/3361
https://github.com/supermerill/SuperSlicer/issues/2326
https://github.com/supermerill/SuperSlicer/issues/3608
https://github.com/supermerill/SuperSlicer/issues/3380
https://github.com/supermerill/SuperSlicer/issues/3271
https://github.com/supermerill/SuperSlicer/issues/3367
https://github.com/supermerill/SuperSlicer/issues/3408
https://github.com/supermerill/SuperSlicer/pull/3415
https://github.com/supermerill/SuperSlicer/issues/3152
https://github.com/supermerill/SuperSlicer/issues/2872
https://github.com/supermerill/SuperSlicer/issues/2696
https://github.com/supermerill/SuperSlicer/issues/2419

**Comment by legend069** [comment]
edited, forgot to add picture.

**Comment by supermerill** [comment]
In Fanmover, you wrote:
```
//                  bug is in here don't flush buffer if it's a new line ?
//                  sometimes once a new line starts it removes the first fan speed command only happens with kickstart - fan_speedup_time
```
if you have a project file that show this bug, please add it here.

For the rest of the code, there is too much debug code and commented thing to merge.
I'll do the rework.

**Comment by supermerill** [comment]
I pushed the rework with the list of settings from here.
please add here any bugs you can find.
I didn't had the time yet to test it widely.

**Comment by legend069** [comment]
> I pushed the rework with the list of settings from here. please add here any bugs you can find. I didn't had the time yet to test it widely.

Hey Meril, welcome back.

my vs code has decided to throw a fit and break on me.
I'll look over your changes as as soon as i get it up and running again :)

**Comment by legend069** [comment]
heres the test project i'll be using.


[ss_test_body_project.zip](https://github.com/supermerill/SuperSlicer/files/13377661/ss_test_body_project.zip)

**Comment by legend069** [comment]
@supermerill do you want me to push the changes I've made to fix bugs as i go or push everything when i can't find/fix any more?

bug fixed so far

- full_fan_speed_layer( as far as I'm aware this has never worked.)
small bug still exists with it. `float factor = float(int(layer_id + 1) - disable_fan_first_layers) / float(full_fan_speed_layer - disable_fan_first_layers);` - factor values get a bit broken with a high `full_fan_speed_layer` number.
`factor`gets broken more when it sets the fan speed `fan_speeds[idx] = std::clamp(int(float(fan_speeds[idx]) * factor + 0.01f), 0, 255);` since it's ramping the speed from that ER value. (might need to have a hidden full_fan_speed_value it can keep ramping up ?)

other bugs with full_fan_speed_layer i think I've squashed.

- missing overhangs_fan_speed from GUI (typo)

**Comment by legend069** [comment]
enabling fan_kickstart and fan_speedup_time seems to be ok now.
fan_speedup_time -only for overhangs sometimes goes back too far? hard to confirm with such small time windows. adding min and max to it's area in print.config.cpp would be good.

main bug: slowdown_below_layer_time doesn't slow down extrusion rates anymore. this was gave me real trouble. at first it vs studio wasn't able to read it's value when inspecting with breakpoints. then out of nowhere it was able to read the values and enter the conditional statements and execute the code, but it still fails to slow down the extrusion speed. maybe this is just my compiler acting strange ?

other bug found unrelated to this PR code changes; //if fan_percentage enabled color view range is incorrect when looking at gcode viewer. it still uses PWM color ranges. written gcode values are correct. so it's only a visual error.

everything else seems to be ok


additions;
I'll look at "Set bridge fan speed for x layers above bridges" when i have some spare time
from https://github.com/supermerill/SuperSlicer/pull/3754

**Comment by supermerill** [comment]
I move the min fan speed to the printer, as it's to take into account the min speed the real printer fan is capable of.
I added a real default speed in the filament cooling.
I changed a little bit the behaviour to take that into account.
I removed a now unused checkbox (run at min speed by default) as it's replaced by the default speed (set 0 to deactivate)

**Pull request closed without merging**
