### PR TITLE
Macos cross compile

### PR DESCRIPTION
**Pull request by claytono**
This is a work in progress for now related to https://github.com/supermerill/SuperSlicer/issues/1227

### CODE REVIEW

**Comment by supermerill** [comment]
when trying to compile arm i have this error:
```
configure: error: could not find a working compiler, see config.log for details
make[2]: *** [dep_GMP-prefix/src/dep_GMP-stamp/dep_GMP-configure] Error 1
make[1]: *** [CMakeFiles/dep_GMP.dir/all] Error 2
```

and then
``` 
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:32:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
#error Unsupported architecture
 ^
```
So I decide to change the virtual machine from 10.5 to 11
now I have this error:
```
configure: error: in `/Users/runner/work/SuperSlicer/SuperSlicer/deps/build/dep_libcurl-prefix/src/dep_libcurl':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make[2]: *** [dep_libcurl-prefix/src/dep_libcurl-stamp/dep_libcurl-configure] Error 1
make[1]: *** [CMakeFiles/dep_libcurl.dir/all] Error 2
```

**Comment by claytono** [comment]
@supermerill yep, it's definitely not working properly quite yet.  Are you building on x86 or arm?

**Comment by supermerill** [comment]
building arm on x86

**Comment by claytono** [comment]
Yep, building arm on x86 is definitely still a work in progress.  The builds take a good while on my x86 Mac, so it's just slow going while I track down all the places changes are need.  I suspect everything using GNU configure will need to be set to cross-compile like the GMP change, although it may be possible to just set them to compile as fat binaries instead, which would be simpler.  That's not possible with GMP since it contains architecture specific assembly and their build process explicitly doesn't support fat binary compiles for arm/x86.

**Comment by claytono** [comment]
I fixed a few other things.  At this point when I compile for arm64 on an x86_64 host, it gets all the way to the final link of the superslicer binary, then fails due to missing neon symbols in the PNG library.  There is configuration in the cmake file already to turn this off on apple silicon, but it's confused by the cross compiling.  I'll work on that next.

**Comment by claytono** [comment]
@supermerill I haven't done a lot of testing, but I did manage to build an arm64 binary on an x86 host, copy that to an arm64 host and load a model and slice it.  It appears to work.

**Comment by claytono** [comment]
@supermerill I've been using the arm64 build for all my slicing for about a week now and not run into any issues.

**Comment by Amacfa** [comment]
> @supermerill I've been using the arm64 build for all my slicing for about a week now and not run into any issues.

Any tips or a blog on how you did this? I am pretty new to all this. How long of a process was it to get nativity on m1?

**Comment by samwiseg0** [comment]
> > @supermerill I've been using the arm64 build for all my slicing for about a week now and not run into any issues.
> 
> Any tips or a blog on how you did this? I am pretty new to all this. How long of a process was it to get nativity on m1?

The latest version has an arm build. You can use that. Make sure to install it to your application folder and then run. `xattr -cr /Applications/SuperSlicer.app`

**Comment by Amacfa** [comment]
> > > @supermerill I've been using the arm64 build for all my slicing for about a week now and not run into any issues.
> > 
> > 
> > Any tips or a blog on how you did this? I am pretty new to all this. How long of a process was it to get nativity on m1?
> 
> The latest version has an [arm build](https://github.com/supermerill/SuperSlicer/releases/tag/2.3.57.7). You can use that. Make sure to install it to your application folder and then run. `xattr -cr /Applications/SuperSlicer.app`

Yes, I had to run that command to get this build to work. Works great now.

but my original comment was aimed more towards “hey I wanna learn how to convert stuff like you did to work natively on m1” 

I wanted to try to get Cura to run natively.

**Comment by supermerill** [comment]
merged

**Pull request closed without merging**
