### PR TITLE
Width change on odd layers

### PR DESCRIPTION
**Pull request by vovodroid**
This commit adds option for change in extrusion width every odd layer: Also it can alternate concentric infill line number.

image

It shifts and overlaps seams between lines for better wall strength.
image
image

Underlying layer seam overlap:
image

### CODE REVIEW

**Comment by supermerill** [comment]
I modified it a bit.
Now it modifies the spacing, as it's dangerous to modify the width without any check (a width musn't be < layer width)Also it Can be a % of the current computed spacing
A 0 value disable it.
Change them to expert-only (and set it as a SuSi setting as i don't think it's in prusa RN)

Tell me if it's okay for you.

**Comment by vovodroid** [comment]
> Tell me if it's okay for you.

Hi, no problem, introduce any changes you think will be good.

**Comment by supermerill** [comment]
add a comment if something is broken or buggy

**Comment by puffofsmoke** [comment]
image
image

late 2.4 edition

Didn't work for me

**Pull request closed without merging**
