### PR TITLE
For review - Remove trailing zeros from gcode feed rates.

### PR DESCRIPTION
**Pull request by martinbudden**
Changed the format of feed rates from fixed point with 3 decimal places to floating point with 8 digits of precision. This means the decimal places are retained when necessary and omitted when not required. So

`G1 X16.288 Y28.463 F3600.000` is written out as `G1 X16.288 Y28.463 F3600`

whereas

`G1 X16.288 Y28.463 F3600.123` is written out as `G1 X16.288 Y28.463 F3600.123`

This makes the GCODE more readable and results in a small saving in GCODE file size (about 1%, or 20KB in a 2MB file).

### CODE REVIEW

**Comment by martinbudden** [comment]
Note the macos build is failing with
```
In file included from /Users/runner/work/SuperSlicer/SuperSlicer/deps/build/dep_wxWidgets-prefix/src/dep_wxWidgets/src/common/settcmn.cpp:30:
/Users/runner/work/SuperSlicer/SuperSlicer/deps/build/dep_wxWidgets-prefix/src/dep_wxWidgets/include/wx/msw/dark_mode.h:3:10: fatal error: 'Windows.h' file not found
#include <Windows.h>
         ^~~~~~~~~~~
```

I don't think this is related to the changes I have made.

**Comment by supermerill** [comment]
Do you have a project where the problem appear?
If i can get rid of the unwanted double->float->double, maybe it's better.

**Comment by martinbudden** [comment]
> Do you have a project where the problem appear?

This is change is not to fix a problem, it's just a minor improvement to the output. When reading gcode I find it annoying to see `F3600.000` rather than `F3600`. It also, as I stated, make the gcode about 1% smaller, which, although not much, is "for free".

> If i can get rid of the unwanted double->float->double, maybe it's better.

I'm not quite sure what you mean by this.

**Comment by supermerill** [comment]
you added
```
#define FLOAT_PRECISION(val, precision) std::defaultfloat << std::setprecision(precision) << (val)
#define F_NUM(val) FLOAT_PRECISION(val, 8)
```
to avoid float rounding problem, right?

to void trailing zeros, you just have to replace
```
 << " F" << F_NUM(m_tool->deretract_speed() * 60.);
```
by
```
 << " F" << (m_tool->deretract_speed() * 60);
```
as `deretract_speed()` return an int

**Comment by martinbudden** [comment]
OK, I've fixed that. Removed `F_NUM` for `retract_speed` and `derectract_speed`, but left `F_NUM` for the travel speeds, since they are not integers.

**Comment by supermerill** [comment]
I made some research, and usgind `default_float` may be dangerous, as it can output the string with a scientific notation
https://en.cppreference.com/w/cpp/io/manip/fixed

what I'm leaning for:

```
#define FLAVOR_IS(val) this->config.gcode_flavor.value == val
#define FLAVOR_IS_NOT(val) this->config.gcode_flavor.value != val
#define COMMENT(comment) if (this->config.gcode_comments.value && !comment.empty()) gcode << " ; " << comment;
#define XYZ_NUM(val) precision_nozero(val, this->config.gcode_precision_xyz.value)
#define F_NUM(val) precision_nozero(val, 8)
#define E_NUM(val) precision_nozero(val, this->config.gcode_precision_e.get_at(m_tool->id()))

namespace Slic3r {

struct precision_nozero
{
    const double value;
    const uint16_t max_precision;

    precision_nozero(double value, uint16_t max_precision)
        : value(value), max_precision(max_precision)
    {}

    void write(std::ostream& stream) const {
        std::streamsize restore = stream.precision(std::min(max_precision, uint16_t(std::ceil(std::abs(std::log10(std::abs(value)))))));
        stream << std::fixed << value;
        stream.precision(restore);
    }
};

inline std::ostream& operator << (std::ostream& stream, const precision_nozero& value) {
    value.write(stream);
    return stream;
}

```

**Comment by supermerill** [comment]
I'm wondering why the retraction speed and deretraction speed are int and all other speeds are doubles.
The retraction_speed setting let us enter a double but it's then trunc as a int... I'm going to let the double go through like for the other speed fields.
imo, it's completely useless to let the user enter float speed value. Who is going to need 2.35 mm/s ? mmm, I may at least keep it as double if someone wants to create a proton-beam printer :-/

**Comment by supermerill** [comment]
Ok, can't find any good way to do what we want. Have to use some custom string processing after the conversion:
```
#define PRECISION(val, precision) to_string_nozero(val, precision)
#define XYZ_NUM(val) PRECISION(val, this->config.gcode_precision_xyz.value)
#define F_NUM(val) PRECISION(val, 8)
#define E_NUM(val) PRECISION(val, this->config.gcode_precision_e.get_at(m_tool->id()))

namespace Slic3r {

std::string to_string_nozero(double value, int32_t max_precision) {
    double intpart;
    if (modf(value, &intpart) == 0.0) {
        //shortcut for int
        return boost::lexical_cast<std::string>(intpart);
    } else {
        std::stringstream ss;
        //first, get the int part, to see how many digit it takes
        int long10 = 0;
        if (intpart > 9)
            long10 = std::floor(std::log10(std::abs(intpart)));
        //set the usable precision: there is only 15-16 decimal digit in a double
        ss << std::fixed << std::setprecision(int(std::min(15 - long10, int(max_precision)))) << value;
        std::string ret = ss.str();
        uint8_t nb_del = 0;
        for (uint8_t i = ret.size() - 1; i > 0; i--) {
            if (ret[i] == '0')
                nb_del++;
            else
                break;
        }
        if (nb_del > 0)
            return ret.substr(0, ret.size() - nb_del);
        else
            return ret;
    }
}
```

Hopefully, this time it works.

**Comment by supermerill** [comment]
Your version has been merged into the latest release (by error)
The update will come for the next version.

**Comment by martinbudden** [comment]
@supermerill , glad you've included this, but for the record I think your solution is overkill.

> I made some research, and using default_float may be dangerous, as it can output the string with a scientific notation

1. True, scientific notation can be output, but it won't be used for the feed rates generated by a slicer, the test code shows this. 
2. I haven't checked this, but surely gcode firmware would be able to handle scientific notation anyway, since it would use library functions to parse the numeric input and these would handle scientific notation.

>BTW, why 8 here ?
> `define F_NUM(val) precision_nozero(val, 8)`

8 is used because normal feed rates are less than 99999, so 8 significant figures give 3 decimal places for any normal feed rate, so the behaviour is as little changed as possible. It also means the test code for fixed point values passes as is.

So, for the record, I think my original solution (with the addition of your change of the integer values to floats) is the best solution.

**Pull request closed without merging**
